/* Generated by re2c 0.5 on Thu Mar 13 14:30:20 2003 */
#line 1 "implicit.re"
//
// implicit.re
//
// $Author$
// $Date$
//
// Copyright (C) 2003 why the lucky stiff
//

#include "syck.h"

#define YYCTYPE     char
#define YYCURSOR    cursor
#define YYMARKER    marker
#define YYLIMIT     limit
#define YYFILL(n)

#define TAG_IMPLICIT( tid )     n->type_id = tid; return;

void
try_tag_implicit( SyckNode *n )
{
    char *cursor, *limit, *marker;
    if ( n->kind != syck_str_kind )
        return;

    cursor = n->data.str->ptr;
    limit = cursor + n->data.str->len;

{
	YYCTYPE yych;
	unsigned int yyaccept;
	static unsigned char yybm[] = {
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0, 224,   0,   0,   0, 
	224, 224, 224, 224, 224, 224, 224, 224, 
	160, 160,   0,   0,   0,   0,   0,   0, 
	  0, 128, 128, 128, 128, 128, 128,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0, 128, 128, 128, 128, 128, 128,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	goto yy0;
yy1:	++YYCURSOR;
yy0:
	if((YYLIMIT - YYCURSOR) < 6) YYFILL(6);
	yych = *YYCURSOR;
	if(yych <= 'S'){
		if(yych <= '0'){
			if(yych <= '+'){
				if(yych <= '\000')	goto yy2;
				if(yych <= '*')	goto yy18;
				goto yy15;
			} else {
				if(yych == '-')	goto yy15;
				if(yych <= '/')	goto yy18;
				goto yy16;
			}
		} else {
			if(yych <= 'F'){
				if(yych <= '9')	goto yy17;
				if(yych <= 'E')	goto yy18;
				goto yy14;
			} else {
				if(yych <= 'M')	goto yy18;
				if(yych <= 'N')	goto yy6;
				if(yych <= 'O')	goto yy12;
				goto yy18;
			}
		}
	} else {
		if(yych <= 'n'){
			if(yych <= 'Y'){
				if(yych <= 'T')	goto yy8;
				if(yych <= 'X')	goto yy18;
				goto yy10;
			} else {
				if(yych == 'f')	goto yy13;
				if(yych <= 'm')	goto yy18;
				goto yy5;
			}
		} else {
			if(yych <= 'x'){
				if(yych <= 'o')	goto yy11;
				if(yych == 't')	goto yy7;
				goto yy18;
			} else {
				if(yych <= 'y')	goto yy9;
				if(yych == '~')	goto yy3;
				goto yy18;
			}
		}
	}
yy2:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy4;
	}
yy3:	yych = *++YYCURSOR;
	if(yych <= '\000')	goto yy64;
yy4:
#line 59
	{   TAG_IMPLICIT( "str" ); }
yy5:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'o')	goto yy37;
	if(yych == 'u')	goto yy67;
	goto yy4;
yy6:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= 'U'){
		if(yych == 'O')	goto yy37;
		if(yych <= 'T')	goto yy4;
		goto yy60;
	} else {
		if(yych <= 'o'){
			if(yych <= 'n')	goto yy4;
			goto yy37;
		} else {
			if(yych == 'u')	goto yy61;
			goto yy4;
		}
	}
yy7:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'r')	goto yy58;
	goto yy4;
yy8:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'R')	goto yy54;
	if(yych == 'r')	goto yy55;
	goto yy4;
yy9:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'e')	goto yy53;
	goto yy4;
yy10:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'E')	goto yy51;
	if(yych == 'e')	goto yy52;
	goto yy4;
yy11:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'f')	goto yy50;
	if(yych == 'n')	goto yy47;
	goto yy4;
yy12:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= 'N'){
		if(yych == 'F')	goto yy45;
		if(yych <= 'M')	goto yy4;
		goto yy47;
	} else {
		if(yych <= 'f'){
			if(yych <= 'e')	goto yy4;
			goto yy46;
		} else {
			if(yych == 'n')	goto yy47;
			goto yy4;
		}
	}
yy13:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'a')	goto yy42;
	goto yy4;
yy14:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == 'A')	goto yy33;
	if(yych == 'a')	goto yy34;
	goto yy4;
yy15:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '/')	goto yy4;
	if(yych <= '0')	goto yy32;
	if(yych <= '9')	goto yy19;
	goto yy4;
yy16:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '/'){
		if(yych <= '\000')	goto yy21;
		if(yych == ',')	goto yy24;
		goto yy4;
	} else {
		if(yych <= '9')	goto yy24;
		if(yych == 'x')	goto yy25;
		goto yy4;
	}
yy17:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yybm[0+yych] & 32)	goto yy19;
	if(yych <= '\000')	goto yy21;
	goto yy4;
yy18:	yych = *++YYCURSOR;
	goto yy4;
yy19:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy20:	if(yybm[0+yych] & 32)	goto yy19;
	if(yych >= '\001')	goto yy2;
yy21:	yych = *++YYCURSOR;
yy22:
#line 57
	{   TAG_IMPLICIT( "int" ); }
yy23:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy24:	if(yybm[0+yych] & 64)	goto yy23;
	if(yych <= '\000')	goto yy30;
	if(yych <= '7')	goto yy2;
	if(yych <= '9')	goto yy19;
	goto yy2;
yy25:	yych = *++YYCURSOR;
	if(yych <= '\000')	goto yy2;
	goto yy27;
yy26:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy27:	if(yybm[0+yych] & 128)	goto yy26;
	if(yych >= '\001')	goto yy2;
yy28:	yych = *++YYCURSOR;
yy29:
#line 53
	{   TAG_IMPLICIT( "int#hex" ); }
yy30:	yych = *++YYCURSOR;
yy31:
#line 55
	{   TAG_IMPLICIT( "int#oct" ); }
yy32:	yych = *++YYCURSOR;
	if(yych <= '\000')	goto yy21;
	if(yych == 'x')	goto yy25;
	goto yy24;
yy33:	yych = *++YYCURSOR;
	if(yych == 'L')	goto yy40;
	goto yy2;
yy34:	yych = *++YYCURSOR;
	if(yych != 'l')	goto yy2;
yy35:	yych = *++YYCURSOR;
	if(yych != 's')	goto yy2;
yy36:	yych = *++YYCURSOR;
	if(yych != 'e')	goto yy2;
yy37:	yych = *++YYCURSOR;
	if(yych >= '\001')	goto yy2;
yy38:	yych = *++YYCURSOR;
yy39:
#line 51
	{   TAG_IMPLICIT( "bool#no" ); }
yy40:	yych = *++YYCURSOR;
	if(yych != 'S')	goto yy2;
yy41:	yych = *++YYCURSOR;
	if(yych == 'E')	goto yy37;
	goto yy2;
yy42:	yych = *++YYCURSOR;
	if(yych != 'l')	goto yy2;
yy43:	yych = *++YYCURSOR;
	if(yych != 's')	goto yy2;
yy44:	yych = *++YYCURSOR;
	if(yych == 'e')	goto yy37;
	goto yy2;
yy45:	yych = *++YYCURSOR;
	if(yych == 'F')	goto yy37;
	goto yy2;
yy46:	yych = *++YYCURSOR;
	if(yych == 'f')	goto yy37;
	goto yy2;
yy47:	yych = *++YYCURSOR;
	if(yych >= '\001')	goto yy2;
yy48:	yych = *++YYCURSOR;
yy49:
#line 49
	{   TAG_IMPLICIT( "bool#yes" ); }
yy50:	yych = *++YYCURSOR;
	if(yych == 'f')	goto yy37;
	goto yy2;
yy51:	yych = *++YYCURSOR;
	if(yych == 'S')	goto yy47;
	goto yy2;
yy52:	yych = *++YYCURSOR;
	if(yych == 's')	goto yy47;
	goto yy2;
yy53:	yych = *++YYCURSOR;
	if(yych == 's')	goto yy47;
	goto yy2;
yy54:	yych = *++YYCURSOR;
	if(yych == 'U')	goto yy57;
	goto yy2;
yy55:	yych = *++YYCURSOR;
	if(yych != 'u')	goto yy2;
yy56:	yych = *++YYCURSOR;
	if(yych == 'e')	goto yy47;
	goto yy2;
yy57:	yych = *++YYCURSOR;
	if(yych == 'E')	goto yy47;
	goto yy2;
yy58:	yych = *++YYCURSOR;
	if(yych != 'u')	goto yy2;
yy59:	yych = *++YYCURSOR;
	if(yych == 'e')	goto yy47;
	goto yy2;
yy60:	yych = *++YYCURSOR;
	if(yych == 'L')	goto yy66;
	goto yy2;
yy61:	yych = *++YYCURSOR;
	if(yych != 'l')	goto yy2;
yy62:	yych = *++YYCURSOR;
	if(yych != 'l')	goto yy2;
yy63:	yych = *++YYCURSOR;
	if(yych >= '\001')	goto yy2;
yy64:	yych = *++YYCURSOR;
yy65:
#line 47
	{   TAG_IMPLICIT( "null" ); }
yy66:	yych = *++YYCURSOR;
	if(yych == 'L')	goto yy63;
	goto yy2;
yy67:	yych = *++YYCURSOR;
	if(yych != 'l')	goto yy2;
yy68:	yych = *++YYCURSOR;
	if(yych == 'l')	goto yy63;
	goto yy2;
}
#line 61


}

