/* Generated by re2c 0.5 on Sat Apr 19 23:46:38 2003 */
#line 1 "lib/token.re"
//
// token.re
//
// $Author$
// $Date$
//
// Copyright (C) 2003 why the lucky stiff
//

#include "syck.h"
#include "gram.h"

//
// Allocate quoted strings in chunks
//
#define QUOTELEN    1024

//
// They do my bidding...
//
#define YYCTYPE     char
#define YYCURSOR    parser->cursor
#define YYMARKER    parser->marker
#define YYLIMIT     parser->limit
#define YYTOKEN     parser->token
#define YYTOKTMP    parser->toktmp
#define YYLINEPTR   parser->lineptr
#define YYLINE      parser->linect
#define YYFILL(n)   syck_parser_read(parser)

//
// Repositions the cursor at `n' offset from the token start.
// Only works in `Header' and `Document' sections.
//
#define YYPOS(n)    YYCURSOR = YYTOKEN + n

//
// Track line numbers
//
#define NEWLINE(ptr)    YYLINE++; YYLINEPTR = ptr + 1

//
// I like seeing the level operations as macros...
//
#define ADD_LEVEL(len)  syck_parser_add_level( parser, len )
#define POP_LEVEL()     syck_parser_pop_level( parser )
#define CURRENT_LEVEL() syck_parser_current_level( parser )

//
// Nice little macro to ensure we're IOPENed to the current level.
// * Only use this macro in the "Document" section *
//
#define ENSURE_IOPEN(last_lvl, to_len, reset) \
        if ( last_lvl->spaces < to_len ) \
        { \
            if ( last_lvl->status == syck_lvl_inline ) \
            { \
                goto Document; \
            } \
            else \
            { \
                ADD_LEVEL( to_len ); \
                if ( reset == 1 ) YYPOS(0); \
                return IOPEN; \
            } \
        } 

//
// Nice little macro to ensure closure of levels.
// * Only use this macro in the "Document" section *
//
#define ENSURE_IEND(last_lvl, to_len) \
        if ( last_lvl->spaces > to_len ) \
        { \
            syck_parser_pop_level( parser ); \
            YYPOS(0); \
            return IEND; \
        }

//
// Concatenates quoted string items and manages allocation
// to the quoted string
//
#define QUOTECAT(s, c, i, l) \
        { \
            if ( i + 1 >= c ) \
            { \
                c += QUOTELEN; \
                S_REALLOC_N( s, char, c ); \
            } \
            s[i++] = l; \
            s[i] = '\0'; \
        }

//
// Tags a plain scalar with a transfer method
// * Use only in "Plain" section *
//
#define RETURN_IMPLICIT() \
    { \
        YYCURSOR = YYTOKTMP; \
        yylval->nodeData = syck_new_str2( YYTOKEN, YYCURSOR - YYTOKEN ); \
        if ( parser->implicit_typing == 1 ) \
        { \
            try_tag_implicit( yylval->nodeData, parser->taguri_expansion ); \
        } \
        return PLAIN; \
    }

//
// Handles newlines, calculates indent
//
#define GOBBLE_UP_INDENT( ict, start ) \
    char *indent = start; \
    NEWLINE(indent); \
    while ( indent < YYCURSOR ) \
    { \
        if ( *(++indent) == '\n' ) \
        { \
            NEWLINE(indent); \
        } \
    } \
    ict = 0; \
    if ( *YYCURSOR == '\0' ) \
    { \
        ict = -1; \
        start = YYCURSOR; \
    } \
    else if ( *YYLINEPTR == ' ' ) \
    { \
        ict = YYCURSOR - YYLINEPTR; \
    }

//
// Argjh!  I hate globals!  Here for yyerror() only!
//
SyckParser *syck_parser_ptr = NULL;

//
// My own re-entrant yylex() using re2c.
// You really get used to the limited regexp.
// It's really nice to not rely on backtracking and such.
//
int
yylex( YYSTYPE *yylval, SyckParser *parser )
{
    syck_parser_ptr = parser;
    if ( YYCURSOR == NULL ) 
    {
        syck_parser_read( parser );
    }

#line 168


    if ( YYLINEPTR != YYCURSOR )
    {
        goto Document;
    }

Header:

    YYTOKEN = YYCURSOR;

{
	YYCTYPE yych;
	unsigned int yyaccept;
	static unsigned char yybm[] = {
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0, 192,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	128,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	goto yy0;
yy1:	++YYCURSOR;
yy0:
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	if(yych <= '\n'){
		if(yych <= '\000')	goto yy4;
		if(yych <= '\t')	goto yy8;
		goto yy6;
	} else {
		if(yych != '-')	goto yy8;
	}
yy2:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '-')	goto yy13;
yy3:
#line 204
	{   YYPOS(0);
                        goto Document; 
                    }
yy4:	yych = *++YYCURSOR;
yy5:
#line 195
	{   SyckLevel *lvl = CURRENT_LEVEL();
                        ENSURE_IEND(lvl, -1);
                        return 0; 
                    }
yy6:	yych = *++YYCURSOR;
	goto yy10;
yy7:
#line 200
	{   int indt_len;
                        GOBBLE_UP_INDENT( indt_len, YYTOKEN );
                        goto Header; }
yy8:	yych = *++YYCURSOR;
	goto yy3;
yy9:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy10:	if(yybm[0+yych] & 64)	goto yy9;
	if(yych != ' ')	goto yy7;
yy11:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy12:	if(yybm[0+yych] & 128)	goto yy11;
	goto yy7;
yy13:	yych = *++YYCURSOR;
	if(yych == '-')	goto yy15;
yy14:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy3;
	}
yy15:	yych = *++YYCURSOR;
	if(yych == '\n')	goto yy16;
	if(yych != ' ')	goto yy14;
yy16:	yych = *++YYCURSOR;
yy17:
#line 181
	{   SyckLevel *lvl = CURRENT_LEVEL();
                        if ( lvl->status == syck_lvl_header )
                        {
                            YYPOS(3);
                            goto Directive; 
                        }
                        else
                        {
                            ENSURE_IEND(lvl, -1);
                            YYPOS(0);
                            return 0; 
                        }
                    }
}
#line 208


Document:
    {
        SyckLevel *lvl = CURRENT_LEVEL();
        if ( lvl->status == syck_lvl_header )
        {
            lvl->status = syck_lvl_implicit;
        }

        YYTOKEN = YYCURSOR;

{
	YYCTYPE yych;
	unsigned int yyaccept;
	static unsigned char yybm[] = {
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0, 160,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	136,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,  16,   0,  16,  64,  64, 
	 80,  80,  80,  80,  80,  80,  80,  80, 
	 80,  80,  64,  64,  64,  64,  64,  64, 
	 64,  64,  64,  64,  64,  64,  64,  64, 
	 64,  64,  64,  64,  64,  64,  64,  64, 
	 64,  64,  64,  64,  64,  64,  64,  64, 
	 64,  64,  64,  64,  64,  64,  64,  64, 
	  0,  64,  64,  64,  64,  64,  64,  64, 
	 64,  64,  64,  64,  64,  64,  64,  64, 
	 64,  64,  64,  64,  64,  64,  64,  64, 
	 64,  64,  64,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	goto yy18;
yy19:	++YYCURSOR;
yy18:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= ','){
		if(yych <= '"'){
			if(yych <= '\n'){
				if(yych <= '\000')	goto yy42;
				if(yych <= '\t')	goto yy44;
			} else {
				if(yych <= '\037')	goto yy44;
				if(yych <= ' ')	goto yy40;
				if(yych <= '!')	goto yy31;
				goto yy35;
			}
		} else {
			if(yych <= '\''){
				if(yych <= '#')	goto yy38;
				if(yych <= '%')	goto yy44;
				if(yych <= '&')	goto yy29;
				goto yy33;
			} else {
				if(yych == '*')	goto yy30;
				if(yych <= '+')	goto yy44;
				goto yy26;
			}
		}
	} else {
		if(yych <= 'Z'){
			if(yych <= ':'){
				if(yych <= '-')	goto yy28;
				if(yych <= '9')	goto yy44;
				goto yy26;
			} else {
				if(yych <= '=')	goto yy44;
				if(yych <= '>')	goto yy37;
				if(yych <= '?')	goto yy28;
				goto yy44;
			}
		} else {
			if(yych <= 'z'){
				if(yych <= '[')	goto yy22;
				if(yych == ']')	goto yy24;
				goto yy44;
			} else {
				if(yych <= '{')	goto yy22;
				if(yych <= '|')	goto yy37;
				if(yych <= '}')	goto yy24;
				goto yy44;
			}
		}
	}
yy20:	yych = *++YYCURSOR;
	goto yy66;
yy21:
#line 222
	{   // Isolate spaces
                        int indt_len;
                        GOBBLE_UP_INDENT( indt_len, YYTOKEN );
                        lvl = CURRENT_LEVEL();

                        // Check for open indent
                        ENSURE_IEND(lvl, indt_len);
                        ENSURE_IOPEN(lvl, indt_len, 0);
                        return INDENT;
                    }
yy22:	yych = *++YYCURSOR;
yy23:
#line 233
	{   ENSURE_IOPEN(lvl, 0, 1);
                        lvl = CURRENT_LEVEL();
                        lvl->status = syck_lvl_inline;
                        return YYTOKEN[0]; 
                    }
yy24:	yych = *++YYCURSOR;
yy25:
#line 239
	{   lvl->status = syck_lvl_implicit;
                        return YYTOKEN[0]; 
                    }
yy26:	yych = *++YYCURSOR;
	if(yych == '\n')	goto yy63;
	if(yych == ' ')	goto yy63;
yy27:
#line 276
	{   ENSURE_IOPEN(lvl, 0, 1);
                        goto Plain; 
                    }
yy28:	yych = *++YYCURSOR;
	if(yych == '\n')	goto yy61;
	if(yych == ' ')	goto yy61;
	goto yy27;
yy29:	yych = *++YYCURSOR;
	if(yych <= '-')	goto yy27;
	if(yych == '`')	goto yy27;
	if(yych <= 'z')	goto yy58;
	goto yy27;
yy30:	yych = *++YYCURSOR;
	if(yybm[0+yych] & 64)	goto yy55;
	goto yy27;
yy31:	yych = *++YYCURSOR;
yy32:
#line 260
	{   goto TransferMethod; }
yy33:	yych = *++YYCURSOR;
yy34:
#line 262
	{   goto SingleQuote; }
yy35:	yych = *++YYCURSOR;
yy36:
#line 264
	{   goto DoubleQuote; }
yy37:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yybm[0+yych] & 32)	goto yy52;
	if(yych <= '+'){
		if(yych == ' ')	goto yy50;
		if(yych <= '*')	goto yy27;
		goto yy47;
	} else {
		if(yych <= '-'){
			if(yych <= ',')	goto yy27;
			goto yy47;
		} else {
			if(yych <= '/')	goto yy27;
			if(yych <= '9')	goto yy47;
			goto yy27;
		}
	}
yy38:	yych = *++YYCURSOR;
yy39:
#line 268
	{   goto Comment; }
yy40:	yych = *++YYCURSOR;
	goto yy46;
yy41:
#line 270
	{   goto Document; }
yy42:	yych = *++YYCURSOR;
yy43:
#line 272
	{   ENSURE_IEND(lvl, -1);
                        return 0; 
                    }
yy44:	yych = *++YYCURSOR;
	goto yy27;
yy45:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy46:	if(yybm[0+yych] & 8)	goto yy45;
	goto yy41;
yy47:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy48:	if(yybm[0+yych] & 32)	goto yy52;
	if(yych <= '+'){
		if(yych == ' ')	goto yy50;
		if(yych >= '+')	goto yy47;
	} else {
		if(yych <= '-'){
			if(yych >= '-')	goto yy47;
		} else {
			if(yych <= '/')	goto yy49;
			if(yych <= '9')	goto yy47;
		}
	}
yy49:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy27;
	}
yy50:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy51:	if(yybm[0+yych] & 32)	goto yy52;
	if(yych == ' ')	goto yy50;
	goto yy49;
yy52:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy53:	if(yybm[0+yych] & 32)	goto yy52;
yy54:
#line 266
	{   YYCURSOR--; goto ScalarBlock; }
yy55:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy56:	if(yybm[0+yych] & 64)	goto yy55;
yy57:
#line 256
	{   yylval->name = syck_strndup( YYTOKEN + 1, YYCURSOR - YYTOKEN - 1 );
                        return ALIAS;
                    }
yy58:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy59:	if(yych <= '-')	goto yy60;
	if(yych == '`')	goto yy60;
	if(yych <= 'z')	goto yy58;
yy60:
#line 252
	{   yylval->name = syck_strndup( YYTOKEN + 1, YYCURSOR - YYTOKEN - 1 );
                        return ANCHOR;
                    }
yy61:	yych = *++YYCURSOR;
yy62:
#line 247
	{   ENSURE_IOPEN(lvl, YYTOKEN - YYLINEPTR, 1);
                        YYPOS(1); 
                        return YYTOKEN[0]; 
                    }
yy63:	yych = *++YYCURSOR;
yy64:
#line 243
	{   YYPOS(1); 
                        return YYTOKEN[0]; 
                    }
yy65:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy66:	if(yych == '\n')	goto yy65;
	if(yych != ' ')	goto yy21;
yy67:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy68:	if(yybm[0+yych] & 128)	goto yy67;
	goto yy21;
}
#line 280

    }

Directive:
    {
        YYTOKTMP = YYCURSOR;

{
	YYCTYPE yych;
	unsigned int yyaccept;
	static unsigned char yybm[] = {
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	 32,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0, 192, 192, 
	192, 192, 192, 192, 192, 192, 192, 192, 
	192, 192, 128, 192, 192, 192, 192, 192, 
	192, 192, 192, 192, 192, 192, 192, 192, 
	192, 192, 192, 192, 192, 192, 192, 192, 
	192, 192, 192, 192, 192, 192, 192, 192, 
	192, 192, 192, 192, 192, 192, 192, 192, 
	  0, 192, 192, 192, 192, 192, 192, 192, 
	192, 192, 192, 192, 192, 192, 192, 192, 
	192, 192, 192, 192, 192, 192, 192, 192, 
	192, 192, 192,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	goto yy69;
yy70:	++YYCURSOR;
yy69:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= ' '){
		if(yych <= '\000')	goto yy71;
		if(yych <= '\037')	goto yy76;
		goto yy74;
	} else {
		if(yych == '%')	goto yy72;
		goto yy76;
	}
yy71:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy73;
	}
yy72:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '-')	goto yy73;
	if(yych == '`')	goto yy73;
	if(yych <= 'z')	goto yy79;
yy73:
#line 293
	{   YYCURSOR = YYTOKTMP;
                        return DOCSEP;
                    }
yy74:	yych = *++YYCURSOR;
	goto yy78;
yy75:
#line 291
	{   goto Directive; }
yy76:	yych = *++YYCURSOR;
	goto yy73;
yy77:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy78:	if(yybm[0+yych] & 32)	goto yy77;
	goto yy75;
yy79:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy80:	if(yybm[0+yych] & 64)	goto yy79;
	if(yych != ':')	goto yy71;
yy81:	yych = *++YYCURSOR;
	if(yybm[0+yych] & 128)	goto yy82;
	goto yy71;
yy82:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy83:	if(yybm[0+yych] & 128)	goto yy82;
yy84:
#line 289
	{   goto Directive; }
}
#line 296


    }

Plain:
    {
        SyckLevel *plvl;
        YYCURSOR = YYTOKEN;
        plvl = CURRENT_LEVEL();

Plain2: 
        YYTOKTMP = YYCURSOR;

Plain3:

{
	YYCTYPE yych;
	unsigned int yyaccept;
	static unsigned char yybm[] = {
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0, 128,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	 64,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	goto yy85;
yy86:	++YYCURSOR;
yy85:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= ','){
		if(yych <= '\n'){
			if(yych <= '\000')	goto yy92;
			if(yych <= '\t')	goto yy98;
			goto yy94;
		} else {
			if(yych == ' ')	goto yy96;
			if(yych <= '+')	goto yy98;
			goto yy91;
		}
	} else {
		if(yych <= '\\'){
			if(yych != ':')	goto yy98;
		} else {
			if(yych <= ']')	goto yy89;
			if(yych == '}')	goto yy89;
			goto yy98;
		}
	}
yy87:	yych = *++YYCURSOR;
	if(yych == '\n')	goto yy104;
	if(yych == ' ')	goto yy104;
yy88:
#line 325
	{   goto Plain2; }
yy89:	yych = *++YYCURSOR;
yy90:
#line 315
	{   if ( plvl->status != syck_lvl_inline ) goto Plain2;
                        RETURN_IMPLICIT();
                    }
yy91:	yych = *++YYCURSOR;
	if(yych == '\n')	goto yy103;
	if(yych == ' ')	goto yy103;
	goto yy88;
yy92:	yych = *++YYCURSOR;
yy93:
#line 319
	{   RETURN_IMPLICIT(); }
yy94:	yych = *++YYCURSOR;
	goto yy102;
yy95:
#line 321
	{   RETURN_IMPLICIT(); }
yy96:	yych = *++YYCURSOR;
	goto yy100;
yy97:
#line 323
	{   goto Plain3; }
yy98:	yych = *++YYCURSOR;
	goto yy88;
yy99:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy100:	if(yybm[0+yych] & 64)	goto yy99;
	goto yy97;
yy101:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy102:	if(yybm[0+yych] & 128)	goto yy101;
	goto yy95;
yy103:	yych = *++YYCURSOR;
	goto yy90;
yy104:	yych = *++YYCURSOR;
yy105:
#line 313
	{   RETURN_IMPLICIT(); }
}
#line 327

    }

Comment:
    {
        YYTOKTMP = YYCURSOR;

{
	YYCTYPE yych;
	unsigned int yyaccept;
	static unsigned char yybm[] = {
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0, 128,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	goto yy106;
yy107:	++YYCURSOR;
yy106:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= '\000')	goto yy108;
	if(yych == '\n')	goto yy110;
	goto yy111;
yy108:	yych = *++YYCURSOR;
yy109:
#line 336
	{   YYCURSOR = YYTOKTMP;
                        goto Document; 
                    }
yy110:	yych = *++YYCURSOR;
	goto yy114;
yy111:	yych = *++YYCURSOR;
yy112:
#line 340
	{   goto Comment; 
                    }
yy113:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy114:	if(yybm[0+yych] & 128)	goto yy113;
	goto yy109;
}
#line 343


    }

SingleQuote:
    {
        int qidx = 0;
        int qcapa = 100;
        char *qstr = S_ALLOC_N( char, qcapa );

SingleQuote2:

{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy115;
yy116:	++YYCURSOR;
yy115:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= '\000')	goto yy119;
	if(yych != '\'')	goto yy120;
yy117:	yych = *++YYCURSOR;
	if(yych == '\'')	goto yy122;
yy118:
#line 361
	{   SyckNode *n = syck_alloc_str();
                        n->data.str->ptr = qstr;
                        n->data.str->len = qidx;
                        yylval->nodeData = n;
                        return PLAIN; 
                    }
yy119:	yych = *++YYCURSOR;
	goto yy118;
yy120:	yych = *++YYCURSOR;
yy121:
#line 368
	{   QUOTECAT(qstr, qcapa, qidx, *(YYCURSOR - 1)); 
                        goto SingleQuote2; 
                    }
yy122:	yych = *++YYCURSOR;
yy123:
#line 357
	{   QUOTECAT(qstr, qcapa, qidx, '\'');
                        goto SingleQuote2; 
                    }
}
#line 372


    }


DoubleQuote:
    {
        int qidx = 0;
        int qcapa = 100;
        char *qstr = S_ALLOC_N( char, qcapa );

DoubleQuote2:

{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy124;
yy125:	++YYCURSOR;
yy124:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= '"'){
		if(yych <= '\000')	goto yy128;
		if(yych <= '!')	goto yy131;
		goto yy130;
	} else {
		if(yych != '\\')	goto yy131;
	}
yy126:	yych = *++YYCURSOR;
	if(yych == '"')	goto yy132;
yy127:
#line 398
	{   QUOTECAT(qstr, qcapa, qidx, *(YYCURSOR - 1)); 
                        goto DoubleQuote2; 
                    }
yy128:	yych = *++YYCURSOR;
yy129:
#line 391
	{   SyckNode *n = syck_alloc_str();
                        n->data.str->ptr = qstr;
                        n->data.str->len = qidx;
                        yylval->nodeData = n;
                        return PLAIN; 
                    }
yy130:	yych = *++YYCURSOR;
	goto yy129;
yy131:	yych = *++YYCURSOR;
	goto yy127;
yy132:	yych = *++YYCURSOR;
yy133:
#line 387
	{   QUOTECAT(qstr, qcapa, qidx, '"');
                        goto DoubleQuote2; 
                    }
}
#line 402

    }

TransferMethod:
    {
        YYTOKTMP = YYCURSOR;

{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy134;
yy135:	++YYCURSOR;
yy134:
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if(yych <= '\n'){
		if(yych <= '\000')	goto yy136;
		if(yych <= '\t')	goto yy139;
		goto yy137;
	} else {
		if(yych == ' ')	goto yy137;
		goto yy139;
	}
yy136:yy137:	yych = *++YYCURSOR;
yy138:
#line 411
	{   SyckLevel *lvl;
                        YYCURSOR = YYTOKTMP;
                        if ( YYCURSOR == YYTOKEN + 1 )
                        {
                            return ITRANSFER;
                        }

                        lvl = CURRENT_LEVEL();

                        //
                        // URL Prefixing
                        //
                        if ( *(YYTOKEN + 1) == '^' )
                        {
                            yylval->name = S_ALLOC_N( char, YYCURSOR - YYTOKEN + strlen( lvl->domain ) );
                            yylval->name[0] = '\0';
                            strcat( yylval->name, lvl->domain );
                            strncat( yylval->name, YYTOKEN + 2, YYCURSOR - YYTOKEN - 2 );
                        }
                        else
                        {
                            char *carat = YYTOKEN + 1;
                            while ( (++carat) < YYCURSOR )
                            {
                                if ( *carat == '^' )
                                    break;
                            }

                            if ( carat < YYCURSOR )
                            {
                                lvl->domain = syck_strndup( YYTOKEN + 1, carat - YYTOKEN - 1 );
                                yylval->name = S_ALLOC_N( char, YYCURSOR - carat + strlen( lvl->domain ) );
                                yylval->name[0] = '\0';
                                strcat( yylval->name, lvl->domain );
                                strncat( yylval->name, carat + 1, YYCURSOR - carat - 1 );
                            }
                            else
                            {
                                yylval->name = syck_strndup( YYTOKEN + 1, YYCURSOR - YYTOKEN - 1 );
                            }
                        }
                        return TRANSFER; 
                    }
yy139:	yych = *++YYCURSOR;
yy140:
#line 455
	{   goto TransferMethod; }
}
#line 457

    }

ScalarBlock:
    {
        int blockType = 0;
        int nlDoWhat = 0;
        int forceIndent = -1;
        char *yyt = YYTOKEN;
        switch ( *yyt )
        {
            case '|': blockType = BLOCK_LIT; break;
            case '>': blockType = BLOCK_FOLD; break;
        }

        while ( ++yyt <= YYCURSOR )
        {
            if ( *yyt == '-' )
            {
                nlDoWhat = NL_CHOMP;
            }
            else if ( *yyt == '+' )
            {
                nlDoWhat = NL_KEEP;
            }
            else if ( isdigit( *yyt ) )
            {
                forceIndent = strtol( yyt, NULL, 10 ) + ( YYTOKEN - YYLINEPTR );
            }
        }

        YYTOKEN = YYCURSOR;

ScalarBlock2:
        YYTOKTMP = YYCURSOR;

{
	YYCTYPE yych;
	unsigned int yyaccept;
	static unsigned char yybm[] = {
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0, 192,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	128,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	goto yy141;
yy142:	++YYCURSOR;
yy141:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= '\000')	goto yy145;
	if(yych != '\n')	goto yy147;
yy143:	yych = *++YYCURSOR;
	goto yy150;
yy144:
#line 495
	{   int indt_len;
                        SyckLevel *lvl;
                        GOBBLE_UP_INDENT( indt_len, YYTOKTMP );
                        lvl = CURRENT_LEVEL();

                        if ( indt_len > lvl->spaces && lvl->status != syck_lvl_block )
                        {
                            ADD_LEVEL( forceIndent > 0 ? forceIndent : indt_len );
                            lvl = CURRENT_LEVEL();
                            lvl->status = syck_lvl_block;
                        }
                        else if ( indt_len < lvl->spaces )
                        {
                            YYCURSOR--;
                            yylval->nodeData = syck_new_str2( YYTOKEN, YYCURSOR - YYTOKEN );  
                            syck_fold_format( yylval->nodeData->data.str, blockType, lvl->spaces, nlDoWhat );
                            POP_LEVEL();
                            return BLOCK;
                        }
                        goto ScalarBlock2;
                    }
yy145:	yych = *++YYCURSOR;
yy146:
#line 518
	{   SyckLevel *lvl = CURRENT_LEVEL();
                        YYCURSOR--;
                        yylval->nodeData = syck_new_str2( YYTOKEN, YYCURSOR - YYTOKEN );  
                        syck_fold_format( yylval->nodeData->data.str, blockType, lvl->spaces, nlDoWhat );
                        POP_LEVEL();
                        return BLOCK; 
                    }
yy147:	yych = *++YYCURSOR;
yy148:
#line 526
	{   goto ScalarBlock2; }
yy149:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy150:	if(yybm[0+yych] & 64)	goto yy149;
	if(yych != ' ')	goto yy144;
yy151:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy152:	if(yybm[0+yych] & 128)	goto yy151;
	goto yy144;
}
#line 528

    }

}

int 
yywrap()
{
    return 1;
}

void 
yyerror( char *msg )
{
    if ( syck_parser_ptr->error_handler == NULL )
        syck_parser_ptr->error_handler = syck_default_error_handler;

    (syck_parser_ptr->error_handler)(syck_parser_ptr, msg);
}

