/* Generated by re2c 0.5 on Thu Mar 13 14:35:31 2003 */
#line 1 "token.re"
//
// token.re
//
// $Author$
// $Date$
//
// Copyright (C) 2003 why the lucky stiff
//

#include "syck.h"
#include "gram.h"

//
// Allocate quoted strings in chunks
//
#define QUOTELEN    1024

//
// They do my bidding...
//
#define YYCTYPE     char
#define YYCURSOR    parser->cursor
#define YYMARKER    parser->marker
#define YYLIMIT     parser->limit
#define YYTOKEN     parser->token
#define YYTOKTMP    parser->toktmp
#define YYLINEPTR   parser->lineptr
#define YYLINE      parser->linect
#define YYFILL(n)   syck_parser_read(parser);

//
// Repositions the cursor at `n' offset from the token start.
// Only works in `Header' and `Document' sections.
//
#define YYPOS(n)    YYCURSOR = YYTOKEN + n;

//
// Track line numbers
//
#define NEWLINE(ptr)    YYLINE++; YYLINEPTR = ptr + 1;

//
// I like seeing the level operations as macros...
//
#define ADD_LEVEL(len)  syck_parser_add_level( parser, len );
#define CURRENT_LEVEL() syck_parser_current_level( parser );

//
// Nice little macro to ensure we're IOPENed to the current level.
// * Only use this macro in the "Document" *
//
#define ENSURE_IOPEN(last_lvl, to_len, reset) \
        if ( last_lvl->spaces < to_len ) \
        { \
            ADD_LEVEL( to_len ); \
            if ( reset == 1 ) YYPOS(0); \
            return IOPEN; \
        } 

//
// Nice little macro to ensure closure of levels.
// * Only use this macro in the "Document" *
//
#define ENSURE_IEND(last_lvl, to_len) \
        if ( last_lvl->spaces > to_len ) \
        { \
            syck_parser_pop_level( parser ); \
            YYPOS(0); \
            return IEND; \
        }

//
// Concatenates quoted string items and manages allocation
// to the quoted string
//
#define QUOTECAT(s, c, i, l) \
        { \
            if ( i + 1 >= c ) \
            { \
                c += QUOTELEN; \
                S_REALLOC_N( s, char, c ); \
            } \
            s[i++] = l; \
            s[i] = '\0'; \
        }

#define CHECK_IMPLICIT() \
    YYCURSOR = YYTOKTMP; \
    yylval->nodeData = syck_new_str2( YYTOKEN, YYCURSOR - YYTOKEN ); \
    try_tag_implicit( yylval->nodeData ); \
    return PLAIN;

//
// Argjh!  I hate globals!  Here for yyerror() only!
//
SyckParser *syck_parser_ptr = NULL;

//
// My own re-entrant yylex() using re2c.
// You really get used to the limited regexp.
// It's really nice to not rely on backtracking and such.
//
int
yylex( YYSTYPE *yylval, SyckParser *parser )
{
    syck_parser_ptr = parser;
    if ( YYCURSOR == NULL ) syck_parser_read( parser );

#line 123


    if ( YYLINEPTR != YYCURSOR )
        goto Document;

Header:

    YYTOKEN = YYCURSOR;

{
	YYCTYPE yych;
	unsigned int yyaccept;
	static unsigned char yybm[] = {
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0, 128,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	128,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	goto yy0;
yy1:	++YYCURSOR;
yy0:
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	if(yych <= '\000')	goto yy2;
	if(yych == '-')	goto yy3;
	goto yy5;
yy2:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy4;
	}
yy3:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych == '-')	goto yy6;
yy4:
#line 136
	{   YYPOS(0);
                        goto Document; 
                    }
yy5:	yych = *++YYCURSOR;
	goto yy4;
yy6:	yych = *++YYCURSOR;
	if(yych != '-')	goto yy2;
yy7:	yych = *++YYCURSOR;
	if(yybm[0+yych] & 128)	goto yy8;
	goto yy2;
yy8:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy9:	if(yybm[0+yych] & 128)	goto yy8;
yy10:
#line 134
	{   goto Directive; }
}
#line 140


Document:

    YYTOKEN = YYCURSOR;

{
	YYCTYPE yych;
	unsigned int yyaccept;
	static unsigned char yybm[] = {
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0, 160,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	 48,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,  64,  64, 
	 64,  64,  64,  64,  64,  64,  64,  64, 
	 64,  64,  64,  64,  64,  64,  64,  64, 
	 64,  64,  64,  64,  64,  64,  64,  64, 
	 64,  64,  64,  64,  64,  64,  64,  64, 
	 64,  64,  64,  64,  64,  64,  64,  64, 
	 64,  64,  64,  64,  64,  64,  64,  64, 
	  0,  64,  64,  64,  64,  64,  64,  64, 
	 64,  64,  64,  64,  64,  64,  64,  64, 
	 64,  64,  64,  64,  64,  64,  64,  64, 
	 64,  64,  64,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	goto yy11;
yy12:	++YYCURSOR;
yy11:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= ','){
		if(yych <= '"'){
			if(yych <= '\n'){
				if(yych <= '\000')	goto yy31;
				if(yych <= '\t')	goto yy33;
			} else {
				if(yych <= '\037')	goto yy33;
				if(yych <= ' ')	goto yy29;
				if(yych <= '!')	goto yy24;
				goto yy27;
			}
		} else {
			if(yych <= '\''){
				if(yych <= '%')	goto yy33;
				if(yych <= '&')	goto yy22;
				goto yy25;
			} else {
				if(yych == '*')	goto yy23;
				if(yych <= '+')	goto yy33;
				goto yy19;
			}
		}
	} else {
		if(yych <= '['){
			if(yych <= ':'){
				if(yych <= '-')	goto yy21;
				if(yych <= '9')	goto yy33;
				goto yy19;
			} else {
				if(yych == '?')	goto yy21;
				if(yych <= 'Z')	goto yy33;
				goto yy15;
			}
		} else {
			if(yych <= 'z'){
				if(yych == ']')	goto yy17;
				goto yy33;
			} else {
				if(yych <= '{')	goto yy15;
				if(yych == '}')	goto yy17;
				goto yy33;
			}
		}
	}
yy13:	yych = *++YYCURSOR;
	goto yy57;
yy14:
#line 148
	{   // Isolate spaces
                        int indt_len;
                        SyckLevel *lvl;
                        char *indent = YYTOKEN;
                        NEWLINE(indent);
                        while ( indent < YYCURSOR ) 
                        { 
                            if ( *(++indent) != '\n' ) 
                                break; 
                            else
                                NEWLINE(indent);
                        }

                        // Calculate indent length
                        lvl = CURRENT_LEVEL();
                        indt_len = 0;
                        if ( *indent == ' ' ) indt_len = YYCURSOR - indent;

                        // Check for open indent
#ifdef REDEBUG
                        printf( "CALLING CURRENT AT INDENT: %d\n", indt_len );
                        printf( "CURSOR: %s\n", YYCURSOR );
#endif
                        ENSURE_IEND(lvl, indt_len);
                        ENSURE_IOPEN(lvl, indt_len, 0);
                        return INDENT;
                    }
yy15:	yych = *++YYCURSOR;
yy16:
#line 176
	{   SyckLevel *lvl = CURRENT_LEVEL();
                        ENSURE_IOPEN(lvl, 0, 1);
                        lvl = CURRENT_LEVEL();
                        lvl->status = syck_lvl_inline;
                        return YYTOKEN[0]; 
                    }
yy17:	yych = *++YYCURSOR;
yy18:
#line 183
	{   SyckLevel *lvl = CURRENT_LEVEL();
                        lvl->status = syck_lvl_implicit;
                        return YYTOKEN[0]; 
                    }
yy19:	yych = *++YYCURSOR;
	if(yych == '\n')	goto yy51;
	if(yych == ' ')	goto yy51;
yy20:
#line 225
	{   SyckLevel *lvl = CURRENT_LEVEL();
                        ENSURE_IOPEN(lvl, 0, 1);
                        goto Plain; 
                    }
yy21:	yych = *++YYCURSOR;
	if(yych == '\n')	goto yy48;
	if(yych == ' ')	goto yy48;
	goto yy20;
yy22:	yych = *++YYCURSOR;
	if(yych <= '-')	goto yy20;
	if(yych == '`')	goto yy20;
	if(yych <= 'z')	goto yy45;
	goto yy20;
yy23:	yych = *++YYCURSOR;
	if(yych <= '-')	goto yy20;
	if(yych == '`')	goto yy20;
	if(yych <= 'z')	goto yy42;
	goto yy20;
yy24:	yych = *++YYCURSOR;
	if(yybm[0+yych] & 32)	goto yy36;
	if(yych <= '-')	goto yy20;
	if(yych == '`')	goto yy20;
	if(yych <= 'z')	goto yy39;
	goto yy20;
yy25:	yych = *++YYCURSOR;
yy26:
#line 212
	{   goto SingleQuote; 
                    }
yy27:	yych = *++YYCURSOR;
yy28:
#line 215
	{   goto DoubleQuote; 
                    }
yy29:	yych = *++YYCURSOR;
	goto yy35;
yy30:
#line 218
	{   goto Document; }
yy31:	yych = *++YYCURSOR;
yy32:
#line 220
	{   SyckLevel *lvl = CURRENT_LEVEL();
                        ENSURE_IEND(lvl, -1);
                        return 0; 
                    }
yy33:	yych = *++YYCURSOR;
	goto yy20;
yy34:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy35:	if(yybm[0+yych] & 16)	goto yy34;
	goto yy30;
yy36:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy37:	if(yybm[0+yych] & 32)	goto yy36;
yy38:
#line 210
	{   return ITRANSFER; }
yy39:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy40:	if(yybm[0+yych] & 64)	goto yy39;
yy41:
#line 206
	{   yylval->name = syck_strndup( YYTOKEN + 1, YYCURSOR - YYTOKEN - 1 );
                        return TRANSFER;
                    }
yy42:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy43:	if(yych <= '-')	goto yy44;
	if(yych == '`')	goto yy44;
	if(yych <= 'z')	goto yy42;
yy44:
#line 202
	{   yylval->name = syck_strndup( YYTOKEN + 1, YYCURSOR - YYTOKEN - 1 );
                        return ALIAS;
                    }
yy45:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy46:	if(yych <= '-')	goto yy47;
	if(yych == '`')	goto yy47;
	if(yych <= 'z')	goto yy45;
yy47:
#line 198
	{   yylval->name = syck_strndup( YYTOKEN + 1, YYCURSOR - YYTOKEN - 1 );
                        return ANCHOR;
                    }
yy48:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy49:	if(yych == '\n')	goto yy48;
	if(yych == ' ')	goto yy48;
yy50:
#line 192
	{   SyckLevel *lvl = CURRENT_LEVEL();
                        ENSURE_IOPEN(lvl, YYTOKEN - YYLINEPTR, 1);
                        YYPOS(1); 
                        return YYTOKEN[0]; 
                    }
yy51:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy52:	if(yych == '\n')	goto yy51;
	if(yych == ' ')	goto yy51;
yy53:
#line 188
	{   YYPOS(1); 
                        return YYTOKEN[0]; 
                    }
yy54:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy55:	if(yych == ' ')	goto yy54;
	goto yy14;
yy56:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy57:	if(yybm[0+yych] & 128)	goto yy56;
	if(yych == ' ')	goto yy54;
	goto yy14;
}
#line 230


Directive:
    {
        YYTOKTMP = YYCURSOR;

{
	YYCTYPE yych;
	unsigned int yyaccept;
	static unsigned char yybm[] = {
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0, 128,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	128,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,  96,  96, 
	 96,  96,  96,  96,  96,  96,  96,  96, 
	 96,  96,  64,  96,  96,  96,  96,  96, 
	 96,  96,  96,  96,  96,  96,  96,  96, 
	 96,  96,  96,  96,  96,  96,  96,  96, 
	 96,  96,  96,  96,  96,  96,  96,  96, 
	 96,  96,  96,  96,  96,  96,  96,  96, 
	  0,  96,  96,  96,  96,  96,  96,  96, 
	 96,  96,  96,  96,  96,  96,  96,  96, 
	 96,  96,  96,  96,  96,  96,  96,  96, 
	 96,  96,  96,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	goto yy58;
yy59:	++YYCURSOR;
yy58:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= '\000')	goto yy60;
	if(yych == '%')	goto yy61;
	goto yy63;
yy60:	YYCURSOR = YYMARKER;
	switch(yyaccept){
	case 0:	goto yy62;
	}
yy61:	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if(yych <= '-')	goto yy62;
	if(yych == '`')	goto yy62;
	if(yych <= 'z')	goto yy64;
yy62:
#line 240
	{   YYCURSOR = YYTOKTMP;
                        return DOCSEP;
                    }
yy63:	yych = *++YYCURSOR;
	goto yy62;
yy64:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy65:	if(yybm[0+yych] & 32)	goto yy64;
	if(yych != ':')	goto yy60;
yy66:	yych = *++YYCURSOR;
	if(yybm[0+yych] & 64)	goto yy67;
	goto yy60;
yy67:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy68:	if(yybm[0+yych] & 128)	goto yy69;
	if(yych <= '-')	goto yy60;
	if(yych == '`')	goto yy60;
	if(yych <= 'z')	goto yy67;
	goto yy60;
yy69:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy70:	if(yybm[0+yych] & 128)	goto yy69;
yy71:
#line 238
	{   goto Directive; }
}
#line 243


    }

Plain:
    {
        SyckLevel *plvl;
        YYCURSOR = YYTOKEN;
        plvl = CURRENT_LEVEL();

Plain2: 
        YYTOKTMP = YYCURSOR;

{
	YYCTYPE yych;
	unsigned int yyaccept;
	static unsigned char yybm[] = {
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0, 192,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	128,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	goto yy72;
yy73:	++YYCURSOR;
yy72:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= '9'){
		if(yych <= '\n'){
			if(yych <= '\000')	goto yy79;
			if(yych <= '\t')	goto yy82;
			goto yy81;
		} else {
			if(yych == ',')	goto yy78;
			goto yy82;
		}
	} else {
		if(yych <= ']'){
			if(yych <= ':')	goto yy74;
			if(yych <= '\\')	goto yy82;
			goto yy76;
		} else {
			if(yych == '}')	goto yy76;
			goto yy82;
		}
	}
yy74:	yych = *++YYCURSOR;
	if(yych == '\n')	goto yy87;
	if(yych == ' ')	goto yy87;
yy75:
#line 271
	{   goto Plain2; }
yy76:	yych = *++YYCURSOR;
yy77:
#line 262
	{   if ( plvl->status != syck_lvl_inline ) goto Plain2;
                        YYCURSOR = YYTOKTMP;
                        CHECK_IMPLICIT();
                    }
yy78:	yych = *++YYCURSOR;
	if(yybm[0+yych] & 128)	goto yy85;
	goto yy75;
yy79:	yych = *++YYCURSOR;
yy80:
#line 267
	{   YYCURSOR = YYTOKTMP;
                        CHECK_IMPLICIT();
                    }
yy81:	yych = *++YYCURSOR;
	goto yy84;
yy82:	yych = *++YYCURSOR;
	goto yy75;
yy83:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy84:	if(yybm[0+yych] & 64)	goto yy83;
	goto yy80;
yy85:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy86:	if(yybm[0+yych] & 128)	goto yy85;
	goto yy77;
yy87:	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy88:	if(yych == '\n')	goto yy87;
	if(yych == ' ')	goto yy87;
yy89:
#line 258
	{   YYCURSOR = YYTOKTMP;
                        CHECK_IMPLICIT();
                    }
}
#line 273

    }

SingleQuote:
    {
        int qidx = 0;
        int qcapa = 100;
        char *qstr = S_ALLOC_N( char, qcapa );

SingleQuote2:

{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy90;
yy91:	++YYCURSOR;
yy90:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= '\000')	goto yy92;
	if(yych == '\'')	goto yy93;
	goto yy95;
yy92:yy93:	yych = *++YYCURSOR;
	if(yych == '\'')	goto yy97;
yy94:
#line 289
	{   SyckNode *n = syck_alloc_str();
                        n->data.str->ptr = qstr;
                        n->data.str->len = qidx;
                        yylval->nodeData = n;
                        return PLAIN; 
                    }
yy95:	yych = *++YYCURSOR;
yy96:
#line 295
	{   QUOTECAT(qstr, qcapa, qidx, *(YYCURSOR - 1)); 
                        goto SingleQuote2; 
                    }
yy97:	yych = *++YYCURSOR;
yy98:
#line 286
	{   QUOTECAT(qstr, qcapa, qidx, '\'');
                        goto SingleQuote2; 
                    }
}
#line 299


    }


DoubleQuote:
    {
        int qidx = 0;
        int qcapa = 100;
        char *qstr = S_ALLOC_N( char, qcapa );

DoubleQuote2:

{
	YYCTYPE yych;
	unsigned int yyaccept;
	goto yy99;
yy100:	++YYCURSOR;
yy99:
	if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if(yych <= '"'){
		if(yych <= '\000')	goto yy101;
		if(yych <= '!')	goto yy106;
		goto yy104;
	} else {
		if(yych == '\\')	goto yy102;
		goto yy106;
	}
yy101:yy102:	yych = *++YYCURSOR;
	if(yych == '"')	goto yy107;
yy103:
#line 325
	{   QUOTECAT(qstr, qcapa, qidx, *(YYCURSOR - 1)); 
                        goto DoubleQuote2; 
                    }
yy104:	yych = *++YYCURSOR;
yy105:
#line 318
	{   SyckNode *n = syck_alloc_str();
                        n->data.str->ptr = qstr;
                        n->data.str->len = qidx;
                        yylval->nodeData = n;
                        return PLAIN; 
                    }
yy106:	yych = *++YYCURSOR;
	goto yy103;
yy107:	yych = *++YYCURSOR;
yy108:
#line 314
	{   QUOTECAT(qstr, qcapa, qidx, '"');
                        goto DoubleQuote2; 
                    }
}
#line 329


    }

}

int 
yywrap()
{
    return 1;
}

void 
yyerror( char *msg )
{
    if ( syck_parser_ptr->error_handler == NULL )
        syck_parser_ptr->error_handler = syck_default_error_handler;

    (syck_parser_ptr->error_handler)(syck_parser_ptr, msg);
}

